### ISSUE TITLE
Add documentation for contributors

### ISSUE THREAD

**Issue by Tardog** [250/Steam-250#31]
As a developer, I want to focus on solving the task at hand, not spent valuable time digging through .travis.yml files to pierce together how to get the site running on my box. The lack of documentation may discourage people to contribute.

**Suggestions**
1. In its current state, the readme is a stub. Add meaningful information about the project and how the different repos relate to each other. Maybe some or all of the information from https://steam250.com/about can be included.
2. Create a CONTRIBUTING.md with detailed instructions for development setup and contribution guidelines.

**Comment by Bilge** [comment]
Thanks for the suggestion. I'll see what I can do.

**Comment by Bilge** [comment]
The main problem here is that, even if you could piece together how to operate the software, you don't have any database snapshots to work with. We used to publish all the snapshots here on GitHub but when that didn't scale I moved them off to a private Google Drive. I'll try to get those snapshots to you ASAP and then work on some documentation.

**Comment by Tardog** [comment]
By using steam-importer, I was able to pull most of the data required for testing and create my own copy of the DB. Not sure how complete it is, though. It was certainly enough to populate all mandatory tables.

Although that approach worked (well, kind of), a downloadable snapshot would be a huge improvement over running the time-consuming import script even once.

Thank you for tackling this. Please let me know if I can help.

**Comment by Bilge** [comment]
That's quite impressive, but even if you create your own snapshot, you still don't have a historic snapshot to display the movement indicators. To help you get started I've manually uploaded the last two snapshots to a new [snapshots tag](https://github.com/250/Steam-250/releases/tag/snapshots). I plan to automate the snapshot uploading so it always contains the latest two snapshots, so you can always replicate the data displayed on the live site locally.

**Comment by Tardog** [comment]
Thank you - that's a huge improvement. I didn't find the time to test the snapshot yet. Automated uploading is nice to have, but not strictly necessary, unless working on some specific issue that only manifests with the most recent data.

**Comment by Bilge** [comment]
I may have time to write some documentation this weekend. Can you help me out by giving me some idea of what you'd like to work on?

**Comment by Tardog** [comment]
By "what you'd like to work on", do you mean specific issues, or are you referring to repos?
The frontend has a lot of open issues, so I would start adding documentation here first.

**Comment by Bilge** [comment]
I'm closing this as complete, due to lack of feedback.
