### ISSUE TITLE
Gunpoint has no Linux icon

### ISSUE THREAD

**Issue by LiamDawe** [250/Steam-250#33]
In your list, Gunpoint: https://store.steampowered.com/app/206190/Gunpoint/ has no Linux icon yet it does support Linux and has the SteamOS icon on Steam to show for it too.

**Comment by Bilge** [comment]
Thanks, that's a bug in the [parser](https://github.com/Provider/Steam). Seems to be because it picks up the demo platforms instead of the full game's platforms. Will fix soon.

**Comment by LiamDawe** [comment]
Excellent, same for SpeedRunners.

**Comment by Bilge** [comment]
This is now fixed via [Provider/Steam#aac3578](https://github.com/Provider/Steam/commit/aac3578353283a8a28aa89bf17e48e3c426c218d) and will be reflected in the next update scheduled in just under 9 hours from now. Thanks again for the report!

**Comment by LiamDawe** [comment]
Fantastic quick work, glad to help point it out :)
