### ISSUE TITLE
Incorrect Platform and Pricing Data for Portal 2

### ISSUE THREAD

**Issue by JJL772** [250/Steam-250#38]
The website lists portal 2 as supporting Windows and OSX only, and it lists the price as $1.99. The pricing and platform support data seems to correspond to "Portal 2 - The Final Hours", presumably because it's listed above "Portal 2" on the store page. 

Here's a screenshot of the Portal 2 store page for reference: 
![image](https://user-images.githubusercontent.com/19717056/105917907-e9d3fb80-5fe7-11eb-984a-ba16d5d7f696.png)

**Comment by Bilge** [comment]
Thanks for reporting. You are indeed correct about the cause of the error. Do you know a good way we can programmatically determine which is the correct price for every game just from inspecting this store page?

**Comment by JJL772** [comment]
Managed to find this: https://steamdb.info/blog/store-prices-api/

Documentation for the big picture storefront API is here: https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI

It'd be nice if valve could provide a better method for this sort of thing, but oh well lol

**Comment by Bilge** [comment]
I'm aware of the appdetails API, but I specifically requested a solution that involves just inspecting the store page because, as noted in that SteamDB piece, the appdetails API is rate limited and thus not suitable for our mass scraping purposes. It is unfortunate, because `packages.0` always points to the primary subid for the game (which represents the correct price), but we need to find some other way.

**Comment by JJL772** [comment]
You could compare the contents of `<div class="apphub_AppName">` with the `game_area_purchase_game_wrapper` div's header element. The real product should exactly match the format `Buy XXX`, where XXX is the content of `<div class="apphub_AppName">`. You could also compare `game_area_purchase_game_wrapper` with the first part of the webpages title, which has the format `XXX on Steam`. Hopefully there are no weird edge cases where these two values differ.

![image](https://user-images.githubusercontent.com/19717056/105930561-b0f35100-5ffe-11eb-8509-60d09573dbde.png)


I apologize if I'm not being clear, kinda difficult to put this into words.

**Comment by Bilge** [comment]
You're perfectly clear, and I had the same thought, except [there are edge cases](https://store.steampowered.com/app/214560).

**Comment by JJL772** [comment]
Ah dang, thanks a lot steam :hurtrealbad: 

Maybe fallback to the steam big picture web API if the title of the game doesn't match any of the buy widgets? I'm pretty much out of ideas here unfortunately.

**Comment by Bilge** [comment]
In the end I decided to [compute the Levenshtein distance](https://github.com/Provider/Steam/blob/60ad858a7df42f2c40f0780674a84462f375d786/src/Scrape/AppDetailsParser.php#L351-L352) between the page title and purchase area title. The one with the smallest distance (most similar to) is presumed to be the primary purchase area and thus used to derive the applicable pricing and platforms information. Fix will be live in a few hours on Steam 250 and a bit later on Club 250.

**Comment by JJL772** [comment]
Wonderful, thanks!
